f._dbapi_connection = engine.raw_connection()

                             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3295, in raw_connection

    return self.pool.connect()

           ^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 447, in connect

    return _ConnectionFairy._checkout(self)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout

    fairy = _ConnectionRecord.checkout(pool)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 711, in checkout

    rec = pool._do_get()

          ^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get

    with util.safe_reraise():

         ^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__

    raise exc_value.with_traceback(exc_tb)

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 175, in _do_get

    return self._create_connection()

           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in _create_connection

    return _ConnectionRecord(self)

           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 673, in __init__

    self.__connect()

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 899, in __connect

    with util.safe_reraise():

         ^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__

    raise exc_value.with_traceback(exc_tb)

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 895, in __connect

    self.dbapi_connection = connection = pool._invoke_creator(self)

                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 646, in connect

    return dialect.connect(*cargs, **cparams)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 626, in connect

    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

(Background on this error at: https://sqlalche.me/e/20/e3q8)